version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: parking
      MYSQL_USER: parking_api
      MYSQL_PASSWORD: parking_api!
      MYSQL_ROOT_PASSWORD: parking_api!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
